### ISSUE TITLE
Lift restrictions on patterns

### ISSUE THREAD

**Issue by gsingh93** [nrc/libhoare#18]
You can lift the restrictions on what patterns can be used in function arguments by creating a closure instead of an inner function. See my [trace](https://github.com/gsingh93/trace) project for an example.

**Comment by nrc** [comment]
This is fixed now. I tried using a closure, but couldn't get it to work (iirc because of issues with the `Self` type. although perhaps I just wasn't trying hard enough). I managed to fix it with some awful hacks using `loop`.
